name: GitHub Profile Trophy

on:
  workflow_dispatch

jobs:
  trophy:
    runs-on: ubuntu-latest

    steps:
      - name: Generate Trophy
        run: |
          mkdir output

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: trophy
          path: output
